# Strings
DEPENDENCY_TYPE = "dependencyType"
AND = 'AND'
XOR = 'XOR'
OR = 'OR'
DEPENDENCIES = 'dependencies'
EXISTENCE = 'existence'
DUPLICATION = 'duplication'
FILE_NAME_PATTERN = 'fileNamePattern'
FILE_EXTENSION = 'fileExtension'
FILE_PROPERTIES = 'fileProperties'
SECTIONS = 'sections'
SECTION = 'section'
PROPERTIES = 'properties'
TYPE = 'type'
NAME = 'name'
FILE_CHECK = 'fileCheck'
DB_CHECK = 'dbCheck'
POSSIBLE_VALUES = 'possibleValues'
NUMBER = 'number'
STRING = 'string'
SET = 'set'
TABLE = 'table'
COLUMN = 'column'
ORDER = 'order'
MYSQL = 'mysql'
ORACLE = 'oracle'
OPTIONAL = 'optional'

#Sets
DEPENDENCY_TYPE_SET = set([AND,OR,XOR])
